name = "receipt-analysis"
compatibility_date = "2024-03-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""

# OpenAI Configuration
OPENAI_API_KEY = ""

# Stripe Configuration
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = ""
NEXT_PUBLIC_STRIPE_BUTTON_ID = ""
STRIPE_SECRET_KEY = "" 